#!/usr/bin/env bash

## Initialize/reinstall site
##
## Usage: fin init-site

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="default"
ENV_PATH="${PROJECT_ROOT}/thunder"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions -----------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#-------------------------- END: Helper functions ------------------------

#-------------------------- Functions --------------------------------

# Make sure composer is installed
ensure_composer_installed ()
{
  echo "Run composer install"
  cd $ENV_PATH
  fin exec composer install
}

# Run gulp
index_search ()
{
  echo "Index search api"
  cd $DOCROOT_PATH
  fin drush sapi-r
  fin drush sapi-i
}
#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

ensure_composer_installed
# Project initialization steps
cd $ENV_PATH
fin drush sql:create -y
fin drush si


echo -e "Open ${yellow}http://${VIRTUAL_HOST}${NC} in your browser to verify the setup."

#-------------------------- END: Execution --------------------------------
